const fs = require('fs');
const path = 'server_v3.js';
let s = fs.readFileSync(path, 'utf8');

function mustReplace(oldText, newText, label) {
  if (s.includes(newText)) return;
  if (!s.includes(oldText)) throw new Error('Dynamic Printful patch marker missing: ' + label);
  s = s.replace(oldText, newText);
}

// Keep the legacy catalogue only as dead data so existing patch steps remain build-compatible.
mustReplace('const SHOP_CATALOG = [', 'const LEGACY_SHOP_CATALOG = [', 'legacy catalogue rename');
mustReplace('const SHOP_MAP = new Map(SHOP_CATALOG.map(p => [p.slug,p]));', 'const LEGACY_SHOP_MAP = new Map(LEGACY_SHOP_CATALOG.map(p => [p.slug,p]));', 'legacy shop map rename');

const dynamicBlock = [
"const SHOP_CATALOG = [];",
"const SHOP_MAP = new Map();",
"const SHOP_CATALOG_TTL_MS = 60 * 1000;",
"let SHOP_CATALOG_CACHE = null;",
"let SHOP_CATALOG_CACHE_AT = 0;",
"let SHOP_CATALOG_REFRESH = null;",
"",
"function printfulPriceToPence(value) {",
"  const n = Number.parseFloat(String(value ?? ''));",
"  return Number.isFinite(n) ? Math.round(n * 100) : null;",
"}",
"",
"const PRINTFUL_SIZE_VALUES = ['XS','S','M','L','XL','2XL','3XL','4XL','5XL','6XL','One Size'];",
"",
"function printfulVariantLabel(v) {",
"  const parts = [];",
"  if (v.color) parts.push(String(v.color));",
"  if (v.size) parts.push(String(v.size));",
"  if (parts.length) return parts.join(' / ');",
"  return String(v.name || v.external_id || v.id || 'Variant');",
"}",
"",
"function printfulVariantMeta(v) {",
"  const label = printfulVariantLabel(v);",
"  const parts = label.split(/\\s*\\/\\s*/).map(x => x.trim()).filter(Boolean);",
"  const sizePart = parts.find(x => PRINTFUL_SIZE_VALUES.some(s => s.toUpperCase() === String(x).toUpperCase())) || String(v.size || '').trim();",
"  const size = String(v.size || sizePart || '').trim();",
"  const nonSize = parts.filter(x => x.toUpperCase() !== size.toUpperCase());",
"  const color = String(v.color || nonSize[0] || '').trim();",
"  return { color: color || null, size: size || null };",
"}",
"",
"function printfulSyncVariantMockup(v) {",
"  const files = Array.isArray(v?.files) ? v.files.filter(Boolean) : [];",
"  const preferred = [",
"    ...files.filter(f => String(f.type || '').toLowerCase() === 'preview'),",
"    ...files.filter(f => f.visible !== false && (f.preview_url || f.thumbnail_url)),",
"    ...files",
"  ];",
"  for (const file of preferred) {",
"    const url = String(file.preview_url || file.thumbnail_url || (String(file.type || '').toLowerCase() === 'preview' ? file.url : '') || '').trim();",
"    if (url) return url;",
"  }",
"  return null;",
"}",
"",
"const PRINTFUL_VARIANT_VISUAL_CACHE_MS = 6 * 60 * 60 * 1000;",
"const PRINTFUL_VARIANT_VISUAL_CACHE = new Map();",
"",
"async function printfulCatalogVariantVisual(catalogVariantId) {",
"  const id = Number(catalogVariantId);",
"  if (!Number.isInteger(id) || id <= 0) return null;",
"  const cached = PRINTFUL_VARIANT_VISUAL_CACHE.get(id);",
"  if (cached && Date.now() - cached.at < PRINTFUL_VARIANT_VISUAL_CACHE_MS) return cached.value;",
"",
"  let value = null;",
"  try {",
"    const j = await printfulRequest('GET', '/v2/catalog-variants/' + id);",
"    const d = j.data || j.result || {};",
"    const image = String(d.image || '').trim();",
"    const color = String(d.color || '').trim();",
"    const size = String(d.size || '').trim();",
"    const productHref = String(d?._links?.product_details?.href || d?._links?.product?.href || '').trim();",
"    const productMatch = productHref.match(/catalog-products\\/(\\d+)/);",
"    const catalogProductId = Number(d.catalog_product_id || d.product_id || productMatch?.[1]);",
"    if (image || color || size || Number.isInteger(catalogProductId)) value = { image_url: image || null, color: color || null, size: size || null, catalog_product_id: Number.isInteger(catalogProductId) ? catalogProductId : null };",
"  } catch {}",
"",
"  if (!value?.image_url) {",
"    try {",
"      const j = await printfulRequest('GET', '/v2/catalog-variants/' + id + '/images');",
"      const rows = Array.isArray(j.data) ? j.data : [];",
"      const first = rows[0]?.images?.find(x => x && x.placement === 'front') || rows[0]?.images?.[0] || null;",
"      const image = String(first?.image_url || first?.background_image || '').trim();",
"      const color = String(rows[0]?.color || '').trim();",
"      if (image || color) value = { ...(value || {}), image_url: image || value?.image_url || null, color: color || value?.color || null, size: value?.size || null };",
"    } catch {}",
"  }",
"",
"  PRINTFUL_VARIANT_VISUAL_CACHE.set(id, { at: Date.now(), value });",
"  return value;",
"}",
"",
"async function enrichPrintfulVariantVisuals(variants) {",
"  const groups = new Map();",
"  for (const v of variants) {",
"    if (!v.catalog_variant_id) continue;",
"    const key = String(v.color || '').trim().toLowerCase() || String(v.catalog_variant_id);",
"    if (!groups.has(key)) groups.set(key, v.catalog_variant_id);",
"  }",
"  const entries = await Promise.all([...groups.entries()].map(async ([key, id]) => [key, await printfulCatalogVariantVisual(id)]));",
"  const visuals = new Map(entries);",
"  return variants.map(v => {",
"    const key = String(v.color || '').trim().toLowerCase() || String(v.catalog_variant_id);",
"    const visual = visuals.get(key);",
"    return { ...v, color: visual?.color || v.color || null, size: v.size || visual?.size || null, catalog_product_id: visual?.catalog_product_id || v.catalog_product_id || null, catalog_image_url: visual?.image_url || null, mockup_url: v.mockup_url || null, image_url: v.mockup_url || v.image_url || visual?.image_url || null };",
"  });",
"}",
"",
"const PRINTFUL_FLAT_MOCKUP_CACHE_MS = 12 * 60 * 60 * 1000;",
"const PRINTFUL_FLAT_MOCKUP_CACHE = new Map();",
"",
"function printfulDesignFiles(files) {",
"  const rows = Array.isArray(files) ? files : [];",
"  const seen = new Set();",
"  const out = [];",
"  for (const f of rows) {",
"    const placement = String(f?.type || f?.placement || '').trim();",
"    if (!placement || placement.toLowerCase() === 'preview') continue;",
"    const imageUrl = String(f?.url || f?.preview_url || '').trim();",
"    if (!imageUrl || seen.has(placement)) continue;",
"    seen.add(placement);",
"    const row = { placement, image_url:imageUrl };",
"    if (f.position && typeof f.position === 'object') row.position = f.position;",
"    out.push(row);",
"  }",
"  return out;",
"}",
"",
"async function printfulFlatBrandedMockups(cacheKey, variants) {",
"  const cached = PRINTFUL_FLAT_MOCKUP_CACHE.get(cacheKey);",
"  if (cached && Date.now() - cached.at < PRINTFUL_FLAT_MOCKUP_CACHE_MS) return cached.value;",
"  const map = new Map();",
"  try {",
"    const catalogProductId = Number(variants.find(v => Number.isInteger(Number(v.catalog_product_id)))?.catalog_product_id);",
"    const catalogVariantIds = [...new Set(variants.map(v => Number(v.catalog_variant_id)).filter(Number.isInteger))];",
"    const designFiles = variants.map(v => v.design_files).find(x => Array.isArray(x) && x.length) || [];",
"    if (!Number.isInteger(catalogProductId) || !catalogVariantIds.length || !designFiles.length) throw new Error('flat_mockup_inputs_missing');",
"    const created = await printfulRequest('POST', '/mockup-generator/create-task/' + catalogProductId, { variant_ids:catalogVariantIds, format:'png', option_groups:['Flat'], files:designFiles });",
"    const taskKey = String(created?.result?.task_key || '').trim();",
"    let result = created?.result || null;",
"    for (let attempt = 0; taskKey && result?.status !== 'completed' && result?.status !== 'failed' && attempt < 10; attempt++) {",
"      await new Promise(resolve => setTimeout(resolve, 750));",
"      const polled = await printfulRequest('GET', '/mockup-generator/task?task_key=' + encodeURIComponent(taskKey));",
"      result = polled?.result || result;",
"    }",
"    if (result?.status !== 'completed') throw new Error('flat_mockup_' + String(result?.status || 'incomplete'));",
"    for (const m of Array.isArray(result.mockups) ? result.mockups : []) {",
"      const url = String(m?.mockup_url || '').trim();",
"      if (!url) continue;",
"      for (const id of Array.isArray(m.variant_ids) ? m.variant_ids : []) {",
"        if (!map.has(Number(id))) map.set(Number(id), url);",
"      }",
"    }",
"  } catch (e) {",
"    console.error('Printful flat branded mockup failed', cacheKey, e.message);",
"  }",
"  PRINTFUL_FLAT_MOCKUP_CACHE.set(cacheKey, { at:Date.now(), value:map });",
"  return map;",
"}",
"","const PRINTFUL_FLAT_BATCH_CACHE_MS = 12 * 60 * 60 * 1000;",
"const PRINTFUL_FLAT_RETRY_MS = 60 * 1000;",
"let PRINTFUL_FLAT_BATCH_CACHE = new Map();",
"let PRINTFUL_FLAT_BATCH_CACHE_AT = 0;",
"let PRINTFUL_FLAT_BATCH_REFRESH = null;",
"",
"function printfulNeedsGarmentOnlyMockup(name) {",
"  return /(?:t-?shirt|\\btee\\b|hoodie|jumper|sweatshirt|sweater|windbreaker|jacket|polo|jersey|tank|shirt|top)/i.test(String(name || ''));",
"}",
"",
"function printfulVariantColourKey(v) {",
"  return String(v?.color || v?.catalog_variant_id || '').trim().toLowerCase();",
"}",
"",
"function printfulExpectedFlatKeys(products) {",
"  const keys = new Set();",
"  for (const p of products.filter(x => printfulNeedsGarmentOnlyMockup(x.name))) {",
"    for (const v of (p.variants || [])) {",
"      const colourKey = printfulVariantColourKey(v);",
"      if (colourKey) keys.add(String(p.sync_product_id) + ':' + colourKey);",
"    }",
"  }",
"  return keys;",
"}",
"",
"function printfulFlatCoverageComplete(products, flatMap) {",
"  const expected = printfulExpectedFlatKeys(products);",
"  if (!expected.size) return true;",
"  for (const key of expected) if (!flatMap.has(key)) return false;",
"  return true;",
"}",
"",
"function applyPrintfulFlatMap(products, flatMap) {",
"  return products.map(p => {",
"    const variants = (p.variants || []).map(v => {",
"      const u = flatMap.get(String(p.sync_product_id) + ':' + printfulVariantColourKey(v)) || null;",
"      return { ...v, product_only_url:u, mockup_url:u || v.mockup_url || null, image_url:u || v.mockup_url || v.image_url || null };",
"    });",
"    const first = variants.find(v => v.product_only_url)?.product_only_url || null;",
"    return { ...p, variants, product_only_url:first, mockup_url:first || p.mockup_url || null, image_url:first || p.mockup_url || p.image_url || null };",
"  });",
"}",
"",
"async function pollPrintfulV2MockupTasks(tasks) {",
"  let current = Array.isArray(tasks) ? tasks : [];",
"  const ids = current.map(t => Number(t?.id)).filter(Number.isInteger);",
"  if (!ids.length) return current;",
"  await new Promise(resolve => setTimeout(resolve, 2500));",
"  for (let attempt = 0; attempt < 20; attempt++) {",
"    const j = await printfulRequest('GET', '/v2/mockup-tasks?id=' + ids.join(','));",
"    const rows = Array.isArray(j.data) ? j.data : (j.data ? [j.data] : []);",
"    if (rows.length) current = rows;",
"    if (current.every(t => ['completed','failed'].includes(String(t?.status || '').toLowerCase()))) break;",
"    await new Promise(resolve => setTimeout(resolve, 1500));",
"  }",
"  return current;",
"}",
"",
"async function buildPrintfulFlatBatchMap(products, seedMap) {",
"  const flatMap = new Map(seedMap || []);",
"  const garments = products.filter(p => {",
"    if (!printfulNeedsGarmentOnlyMockup(p.name) || !Number.isInteger(Number(p.sync_product_id))) return false;",
"    const keys = new Set((p.variants || []).map(v => printfulVariantColourKey(v)).filter(Boolean));",
"    for (const colourKey of keys) if (!flatMap.has(String(p.sync_product_id) + ':' + colourKey)) return true;",
"    return false;",
"  });",
"  if (!garments.length) return flatMap;",
"",
"  const mineResponse = await printfulRequest('GET', '/v2/products?limit=100');",
"  const mine = Array.isArray(mineResponse.data) ? mineResponse.data : [];",
"  const bySync = new Map();",
"  for (const my of mine) {",
"    for (const pub of Array.isArray(my?.published_to_stores) ? my.published_to_stores : []) {",
"      const sid = Number(pub?.sync_product_id);",
"      if (Number.isInteger(sid)) bySync.set(sid, my);",
"    }",
"  }",
"",
"  const prepared = [];",
"  for (const p of garments) {",
"    const my = bySync.get(Number(p.sync_product_id));",
"    const myProductId = Number(my?.id);",
"    const catalogProductId = Number(my?.catalog_product_id);",
"    const placements = Array.isArray(my?.placements) ? my.placements.filter(Boolean) : [];",
"    if (!my || !Number.isInteger(myProductId) || !Number.isInteger(catalogProductId) || !placements.length) continue;",
"",
"    const variantsResponse = await printfulRequest('GET', '/v2/products/' + myProductId + '/variants?limit=100');",
"    const myVariants = Array.isArray(variantsResponse.data) ? variantsResponse.data : [];",
"    const myVariantByCatalog = new Map(myVariants.map(v => [Number(v.catalog_variant_id), Number(v.id)]).filter(([c,m]) => Number.isInteger(c) && Number.isInteger(m)));",
"    const representatives = [];",
"    const seenColours = new Set();",
"    for (const v of (p.variants || [])) {",
"      const colourKey = printfulVariantColourKey(v);",
"      const catalogId = Number(v.catalog_variant_id);",
"      const myVariantId = myVariantByCatalog.get(catalogId);",
"      if (!colourKey || seenColours.has(colourKey) || !Number.isInteger(catalogId) || !Number.isInteger(myVariantId)) continue;",
"      if (flatMap.has(String(p.sync_product_id) + ':' + colourKey)) { seenColours.add(colourKey); continue; }",
"      seenColours.add(colourKey);",
"      representatives.push({ colourKey, catalogId, myVariantId });",
"    }",
"    if (!representatives.length) continue;",
"",
"    const styleResponse = await printfulRequest('GET', '/v2/catalog-products/' + catalogProductId + '/mockup-styles?limit=100&default_mockup_styles=true&selling_region_name=uk');",
"    const groups = Array.isArray(styleResponse.data) ? styleResponse.data : [];",
"    const styles = groups.flatMap(g => (Array.isArray(g?.mockup_styles) ? g.mockup_styles : []).map(m => ({...m, placement:g.placement})));",
"    const flatFront = styles.find(m => /^flat$/i.test(String(m.category_name || '')) && /front/i.test(String(m.view_name || m.placement || '')));",
"    const flatAny = styles.find(m => /^flat$/i.test(String(m.category_name || '')));",
"    const chosen = flatFront || flatAny;",
"    if (!chosen?.id) continue;",
"",
"    const catalogToColour = new Map(representatives.map(r => [r.catalogId, r.colourKey]));",
"    prepared.push({",
"      product:p,",
"      style_id:Number(chosen.id),",
"      catalogToColour,",
"      request:{ source:'product', mockup_style_ids:[Number(chosen.id)], product_id:myProductId, variant_ids:representatives.map(r => r.myVariantId), placements }",
"    });",
"  }",
"",
"  for (let i = 0; i < prepared.length; i++) {",
"    const ref = prepared[i];",
"    const created = await printfulRequest('POST', '/v2/mockup-tasks', { format:'png', mockup_width_px:1200, products:[ref.request] });",
"    const tasks = Array.isArray(created.data) ? created.data : (created.data ? [created.data] : []);",
"    const finished = await pollPrintfulV2MockupTasks(tasks);",
"    const task = finished[0];",
"    if (String(task?.status || '').toLowerCase() === 'completed') {",
"      for (const row of Array.isArray(task?.catalog_variant_mockups) ? task.catalog_variant_mockups : []) {",
"        const catalogId = Number(row?.catalog_variant_id);",
"        const colourKey = ref.catalogToColour.get(catalogId);",
"        const mockups = Array.isArray(row?.mockups) ? row.mockups : [];",
"        const picked = mockups.find(m => Number(m?.style_id) === ref.style_id) || mockups[0] || null;",
"        const url = String(picked?.mockup_url || '').trim();",
"        if (colourKey && url) flatMap.set(String(ref.product.sync_product_id) + ':' + colourKey, url);",
"      }",
"    }",
"    if (i + 1 < prepared.length) await new Promise(resolve => setTimeout(resolve, 1500));",
"  }",
"  return flatMap;",
"}",
"",
"async function enrichPrintfulFlatProductMockups(products) {",
"  const complete = printfulFlatCoverageComplete(products, PRINTFUL_FLAT_BATCH_CACHE);",
"  const age = Date.now() - PRINTFUL_FLAT_BATCH_CACHE_AT;",
"  if (complete && PRINTFUL_FLAT_BATCH_CACHE_AT && age < PRINTFUL_FLAT_BATCH_CACHE_MS) return applyPrintfulFlatMap(products, PRINTFUL_FLAT_BATCH_CACHE);",
"  if (!complete && PRINTFUL_FLAT_BATCH_CACHE_AT && age < PRINTFUL_FLAT_RETRY_MS) return applyPrintfulFlatMap(products, PRINTFUL_FLAT_BATCH_CACHE);",
"  if (!PRINTFUL_FLAT_BATCH_REFRESH) {",
"    PRINTFUL_FLAT_BATCH_REFRESH = (async () => {",
"      try {",
"        let map = await buildPrintfulFlatBatchMap(products, PRINTFUL_FLAT_BATCH_CACHE);",
"        if (!printfulFlatCoverageComplete(products, map)) {",
"          const legacy = await buildPrintfulLegacyFlatMap(products);",
"          for (const [key, url] of legacy) if (!map.has(key) && url) map.set(key, url);",
"        }",
"        PRINTFUL_FLAT_BATCH_CACHE = map;",
"        PRINTFUL_FLAT_BATCH_CACHE_AT = Date.now();",
"        console.log('Printful flat product-only mockups refreshed', map.size, 'of', printfulExpectedFlatKeys(products).size, 'colour variants');",
"        return map;",
"      } catch (e) {",
"        console.error('Printful flat product-only batch failed', e.message);",
"        PRINTFUL_FLAT_BATCH_CACHE_AT = Date.now();",
"        return PRINTFUL_FLAT_BATCH_CACHE;",
"      } finally {",
"        PRINTFUL_FLAT_BATCH_REFRESH = null;",
"      }",
"    })();",
"  }",
"  const map = await PRINTFUL_FLAT_BATCH_REFRESH;",
"  return applyPrintfulFlatMap(products, map);",
"}",
"","async function buildPrintfulLegacyFlatMap(products) {",
"  const map = new Map();",
"  for (const p of products.filter(x => printfulNeedsGarmentOnlyMockup(x.name))) {",
"    try {",
"      const generated = await printfulFlatBrandedMockups('legacy-' + String(p.sync_product_id), p.variants || []);",
"      const seen = new Set();",
"      for (const v of (p.variants || [])) {",
"        const colourKey = printfulVariantColourKey(v);",
"        const catalogId = Number(v.catalog_variant_id);",
"        if (!colourKey || seen.has(colourKey) || !Number.isInteger(catalogId)) continue;",
"        const url = generated.get(catalogId) || null;",
"        if (url) { map.set(String(p.sync_product_id) + ':' + colourKey, url); seen.add(colourKey); }",
"      }",
"    } catch (e) { console.error('Printful legacy flat mockup failed', p.name, e.message); }",
"    await new Promise(resolve => setTimeout(resolve, 800));",
"  }",
"  return map;",
"}",
"","async function listAllPrintfulStoreProducts() {",
"  const out = [];",
"  let offset = 0;",
"  const limit = 100;",
"  for (let page = 0; page < 20; page++) {",
"    const j = await printfulRequest('GET', '/store/products?limit=' + limit + '&offset=' + offset);",
"    const rows = Array.isArray(j.result) ? j.result : [];",
"    out.push(...rows);",
"    const total = Number(j.paging?.total || out.length);",
"    if (!rows.length || out.length >= total || rows.length < limit) break;",
"    offset += rows.length;",
"  }",
"  return out;",
"}",
"",
"async function fetchPrintfulShopCatalog() {",
"  const summaries = (await listAllPrintfulStoreProducts()).filter(p => p && p.is_ignored !== true);",
"  const details = [];",
"  for (let i = 0; i < summaries.length; i += 8) {",
"    const batch = summaries.slice(i, i + 8);",
"    const rows = await Promise.all(batch.map(async summary => {",
"      try {",
"        const j = await printfulRequest('GET', '/store/products/' + encodeURIComponent(String(summary.id)));",
"        return { summary, data: j.result || {} };",
"      } catch (e) {",
"        console.error('Printful product detail failed', summary.id, e.message);",
"        return null;",
"      }",
"    }));",
"    details.push(...rows.filter(Boolean));",
"  }",
"  const products = [];",
"  for (const {summary, data} of details) {",
"    const product = data.sync_product || summary || {};",
"    const rawVariants = (data.sync_variants || [])",
"      .filter(v => v && v.is_ignored !== true && v.synced !== false && v.availability_status !== 'discontinued')",
"      .map(v => {",
"        const meta = printfulVariantMeta(v);",
"        return {",
"          id: String(v.id),",
"          label: printfulVariantLabel(v),",
"          sync_variant_id: Number(v.id),",
"          catalog_variant_id: Number(v.variant_id),",
"          color: meta.color,",
"          size: meta.size,",
"          design_files: printfulDesignFiles(v.files),",
"          mockup_url: printfulSyncVariantMockup(v),",
"          image_url: printfulSyncVariantMockup(v),",
"          price: printfulPriceToPence(v.retail_price)",
"        };",
"      })",
"      .filter(v => Number.isInteger(v.price) && v.price >= 0 && Number.isInteger(v.sync_variant_id));",
"    if (!rawVariants.length) continue;",
"    const variants = await enrichPrintfulVariantVisuals(rawVariants);",
"    const prices = variants.map(v => v.price);",
"    products.push({",
"      sync_product_id: Number(product.id || summary.id),",
"      slug: 'pf-' + String(product.id || summary.id),",
"      name: String(product.name || summary.name || 'Afiléon Motorsport Product').trim(),",
"      description: String(product.description || 'Made-to-order Afiléon Motorsport product.'),",
"      price: Math.min(...prices),",
"      price_from: Math.min(...prices),",
"      product_only_url: null,",
"      mockup_url: variants.find(v => v.mockup_url)?.mockup_url || product.thumbnail_url || summary.thumbnail_url || null,",
"      image_url: variants.find(v => v.mockup_url)?.mockup_url || product.thumbnail_url || summary.thumbnail_url || null,",
"      stock: null,",
"      featured: true,",
"      collection: 'teamwear',",
"      variants",
"    });",
"  }",
"  return products;",
"}",
"",
"async function getPrintfulShopCatalog(force = false) {",
"  if (!PRINTFUL_API_TOKEN) return [];",
"  if (!force && Array.isArray(SHOP_CATALOG_CACHE) && Date.now() - SHOP_CATALOG_CACHE_AT < SHOP_CATALOG_TTL_MS) return SHOP_CATALOG_CACHE;",
"  if (SHOP_CATALOG_REFRESH) return SHOP_CATALOG_REFRESH;",
"  SHOP_CATALOG_REFRESH = (async () => {",
"    try {",
"      const base = await fetchPrintfulShopCatalog();",
"      if (!base.length) throw new Error('printful_catalog_empty');",
"      const next = await enrichPrintfulFlatProductMockups(base);",
"      SHOP_CATALOG_CACHE = next;",
"      SHOP_CATALOG_CACHE_AT = Date.now();",
"      console.log('Printful shop catalogue refreshed', next.length, 'products');",
"      return next;",
"    } catch (e) {",
"      console.error('Printful shop catalogue refresh failed', e.message);",
"      return Array.isArray(SHOP_CATALOG_CACHE) ? SHOP_CATALOG_CACHE : [];",
"    } finally {",
"      SHOP_CATALOG_REFRESH = null;",
"    }",
"  })();",
"  return SHOP_CATALOG_REFRESH;",
"}",
].join('\n');

const printfulMarker = "async function ensurePrintfulWebhook() {";
if (!s.includes('const SHOP_CATALOG_TTL_MS = 60 * 1000;')) {
  if (!s.includes('async function printfulRequest(')) throw new Error('Dynamic Printful patch marker missing: printfulRequest');
  s = s.replace(printfulMarker, dynamicBlock + '\n\n' + printfulMarker);
}

const normaliseStart = 'function normaliseShopItems(input) {';
const normaliseEnd = '\n\nasync function submitPrintfulOrder';
const ns = s.indexOf(normaliseStart);
const ne = s.indexOf(normaliseEnd, ns);
if (ns < 0 || ne < 0) throw new Error('Dynamic Printful patch marker missing: normaliseShopItems');
const normaliseNew = [
  'async function normaliseShopItems(input) {',
  "  const items = Array.isArray(input) ? input : [];",
  "  if (!items.length) throw new Error('empty_basket');",
  "  const catalog = await getPrintfulShopCatalog();",
  "  const map = new Map(catalog.map(p => [p.slug, p]));",
  "  return items.map(raw => {",
  "    const slug = clean(raw.slug, 100);",
  "    const variantId = clean(raw.variant_id || raw.variant || '', 60);",
  "    const quantity = Math.max(1, Math.min(10, Number(raw.quantity || 1)));",
  "    const product = map.get(slug);",
  "    const variant = product?.variants?.find(v => v.id === variantId);",
  "    if (!product || !variant || !Number.isInteger(variant.price)) throw new Error('invalid_product_variant');",
  "    return { slug, name: product.name, variant_id: variant.id, variant_label: variant.label, sync_variant_id: variant.sync_variant_id, quantity, unit_price: variant.price };",
  "  });",
  '}',
].join('\n');
s = s.slice(0, ns) + normaliseNew + s.slice(ne);

const shopStart = "app.get('/api/shop/products'";
const seasonStart = "app.get('/api/season'";
const ss = s.indexOf(shopStart);
const se = s.indexOf(seasonStart, ss);
if (ss < 0 || se < 0) throw new Error('Dynamic Printful patch marker missing: shop routes');
const shopRoutes = [
  "app.get('/api/shop/products', async (_q,res) => {",
  "  const catalog = await getPrintfulShopCatalog();",
  "  return res.json({",
  "    products: catalog.map(p => ({ slug:p.slug,name:p.name,description:p.description,price:p.price,price_from:p.price_from,product_only_url:p.product_only_url||null,mockup_url:p.mockup_url||null,image_url:p.product_only_url||p.mockup_url||p.image_url,stock:null,featured:p.featured,collection:p.collection,variants:p.variants.map(v => ({id:v.id,label:v.label,color:v.color||null,size:v.size||null,catalog_image_url:v.catalog_image_url||null,design_files:Array.isArray(v.design_files)?v.design_files:[],product_only_url:v.product_only_url||null,mockup_url:v.mockup_url||null,image_url:v.product_only_url||v.mockup_url||v.image_url||p.product_only_url||p.mockup_url||p.image_url||null,price:v.price})) })),",
  "    delivery_price:SHOP_DELIVERY_GBP,",
  "    currency:'GBP',",
  "    checkout_live:SHOP_CHECKOUT_LIVE && catalog.length > 0,",
  "    checkout_requested:SHOP_CHECKOUT_REQUESTED,",
  "    stripe_live:STRIPE_LIVE_KEY,",
  "    printful_connected:!!PRINTFUL_API_TOKEN,",
  "    catalogue_source:'printful',",
  "    catalogue_refreshed_at:SHOP_CATALOG_CACHE_AT ? new Date(SHOP_CATALOG_CACHE_AT).toISOString() : null,",
  "    fulfilment_live:PRINTFUL_FULFILMENT_LIVE",
  "  });",
  "});",
  '',
  "app.post('/api/shop/checkout', async (req,res,next) => {",
  "  if (!Array.isArray(req.body?.items)) return next();",
  "  if (!stripe) return res.status(503).json({ error:'stripe_not_configured' });",
  "  if (!SHOP_CHECKOUT_LIVE) return res.status(503).json({ error:'shop_not_live', detail: STRIPE_LIVE_KEY ? 'Merchandise checkout is not enabled yet.' : 'Merchandise checkout is ready but live Stripe payments have not been enabled yet.' });",
  "  let items;",
  "  try { items = await normaliseShopItems(req.body.items); } catch (e) { return res.status(400).json({ error:e.message==='empty_basket'?'empty_basket':'invalid_product_variant' }); }",
  "  const total = items.reduce((n,x) => n + x.unit_price * x.quantity, 0);",
  "  const id = token('ord');",
  "  try {",
  "    await pool.query(\"INSERT INTO orders(public_id,status,total,items,stock_reserved,provider,fulfilment_status) VALUES($1,'pending',$2,$3::jsonb,false,'printful','awaiting_payment')\", [id,total,JSON.stringify(items)]);",
  "    const lines = items.map(x => ({ quantity:x.quantity, price_data:{currency:'gbp',unit_amount:x.unit_price,tax_behavior:'exclusive',product_data:{name:x.name + ' — ' + x.variant_label}} }));",
  "    const session = await stripe.checkout.sessions.create({",
  "      mode:'payment',",
  "      success_url:SITE_URL + '/shop-success.html?order=' + id + '&session_id={CHECKOUT_SESSION_ID}',",
  "      cancel_url:SITE_URL + '/shop.html?cancelled=1',",
  "      automatic_tax:{enabled:true},",
  "      billing_address_collection:'required',",
  "      shipping_address_collection:{allowed_countries:['GB']},",
  "      shipping_options:[{shipping_rate_data:{type:'fixed_amount',fixed_amount:{amount:SHOP_DELIVERY_GBP,currency:'gbp'},display_name:'UK delivery'}}],",
  "      phone_number_collection:{enabled:true},",
  "      line_items:lines,",
  "      metadata:{kind:'shop_order',order_id:id},",
  "      payment_intent_data:{metadata:{kind:'shop_order',order_id:id}}",
  "    }, {idempotencyKey:'shop_' + id});",
  "    await pool.query('UPDATE orders SET stripe_checkout_session_id=$1,updated_at=now() WHERE public_id=$2',[session.id,id]);",
  "    return res.json({order_id:id,checkout_url:session.url,delivery_price:SHOP_DELIVERY_GBP});",
  "  } catch (e) {",
  "    console.error('Shop checkout',e);",
  "    await pool.query(\"UPDATE orders SET status='failed',fulfilment_error=$1,updated_at=now() WHERE public_id=$2\",[clean(e.message,1000),id]).catch(()=>{});",
  "    return res.status(500).json({error:'checkout_creation_failed'});",
  "  }",
  "});",
  '',
  "app.get('/api/shop/orders/:id', async (req,res) => {",
  "  const {rows} = await pool.query('SELECT public_id,status,total,customer_email,provider,printful_order_id,fulfilment_status,tracking_number,tracking_url,fulfilment_error,created_at,updated_at FROM orders WHERE public_id=$1 LIMIT 1',[req.params.id]);",
  "  if (!rows[0]) return res.status(404).json({error:'not_found'});",
  "  res.json(rows[0]);",
  "});",
  '',
].join('\n');
s = s.slice(0, ss) + shopRoutes + s.slice(se);

fs.writeFileSync(path, s);
console.log('Applied dynamic Printful catalogue patch');